name: Setup Initial Infrastructure

on:
  workflow_dispatch:
    inputs:
      create_state_bucket:
        description: 'Create Terraform state bucket'
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  actions: read

env:
  AWS_REGION: us-east-1

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run Infrastructure Setup
        run: |
          chmod +x scripts/setup-infrastructure.sh
          ./scripts/setup-infrastructure.sh